### ISSUE TITLE
const lvalue reference instead of const rvalue reference

### ISSUE THREAD

**Issue by changkhothuychung** [bemanproject/inplace_vector#10]
Should this argument be a const lvalue reference instead? 

```cpp
inplace_vector_destruct_base &
  operator=(const inplace_vector_destruct_base &&other) noexcept(
      std::is_nothrow_move_constructible_v<T> &&
      std::is_nothrow_move_assignable_v<T>) {
    size_ = other.size_;
    other.size_ = nullptr;
  }
 ```
 
 https://github.com/beman-project/inplace_vector/blob/main/include/beman/inplace_vector/inplace_vector.hpp#L74C3-L80C4

**Comment by wusatosi** [comment]
I think you're right here, const r-value doesn't make sense

**Comment by wusatosi** [comment]
Closed due to switching implementation
