### ISSUE TITLE
Moving to an alternative implementation

### ISSUE THREAD

**Issue by wusatosi** [bemanproject/inplace_vector#39]
I have gotten the permission from @camio  to adopt the [reference implementation](https://godbolt.org/z/5P78aG5xE) by @gnzlbg in the paper.

I propose we set-a-side current implementation as there's significant work for fixing and catching up.

Reference implementation will start to be synced in [ref-impl](https://github.com/bemanproject/inplace_vector/tree/ref-impl) branch. I will open a PR once it is reasonably integrated with current system.

Meanwhile, I suggest we halt all progress on PRs related to `include/.../inplace_vector.hpp` in the main branch.

Feel free (and please) help me by writing PRs against the ref_impl branch.

Task list:

Main implementation:
- [x] sync implementation to ref-impl
- [x] update cmake script if needed
- [x] lint implementation
- [x] update name space to beman

Test suite:
- [x] sync tests (or subset of test) to ref-impl
- [x] pass all tests

Documentation:
- [x] Determine new minimum C++ standard

@camio @DeveloperPaul123 @ClausKlein @jbab

**Comment by ClausKlein** [comment]
## merged with open review?

What kind of process do you do?

**Comment by ClausKlein** [comment]
i.e. https://github.com/bemanproject/inplace_vector/pull/43/files/40d3378cd82cb217a9810e5255abcffe48dd0a63#r1868191967
